### ISSUE TITLE
Nope to the copyright police :)

### ISSUE THREAD

**Issue by davidsneighbour** [danielfdickinson/dfd-template#13]
Naaaaah, feel free to remove the paragraph about the copyright of the kollitsch.dev repo for configurations. I appreciate the @davidsneighbour mention. All else is open source and just configs. You will find them at many places and I probably also just took them from the pre-commit-website or read through the documentation (especially where it is about trailing spaces in markdown files, that was some google searching well done). 

My weird license on the [kollitsch.dev](https://github.com/davidsneighbour/kollitsch.dev) repository is only to make sure that my theme and content is not re-used by people just cloning and publishing the repo. All else is more or less free to use, especially configurations I set. Also: don't sue me if they break your setup :p 

If you find anything in my theme files that you like feel free to take that part too, just not the whole theme.

**Comment by danielfdickinson** [comment]
Ok, thank you. I had the 'where applicable' phrase on the configs because configs are not particularly copyrightable (nor do I want to do so, really), but I will definitely keep the acknowledgement. The other repo (wordlists) you might just have got a notification for as well.
